[bell]
animation = "EaseOutExpo"
color = "#ffffff"
command = "None"
duration = 0

[colors]
[colors.bright]
black = "#75715e"
blue = "#66d9ef"
cyan = "#a1efe4"
green = "#a6e22e"
magenta = "#ae81ff"
red = "#f92672"
white = "#f9f8f5"
yellow = "#f4bf75"
[colors.normal]
black = "#272822"
blue = "#66d9ef"
cyan = "#a1efe4"
green = "#a6e22e"
magenta = "#ae81ff"
red = "#f92672"
white = "#f8f8f2"
yellow = "#f4bf75"
[colors.primary]
background = "#171714"
foreground = "#f8f8f2"

[cursor]
blink_interval = 750
thickness = 0.15
unfocused_hollow = true
[cursor.style]
shape = "Block"

[debug]
log_level = "Warn"
persistent_logging = false
print_events = false
render_timer = false

[env]
TERM = "xterm-256color"

[font]
size = 7.0
[font.bold]
family = "monospace"
style = "Bold"
[font.bold_italic]
family = "monospace"
style = "Bold Italic"
[font.glyph_offset]
x = 0
y = 0
[font.italic]
family = "monospace"
style = "Italic"
[font.normal]
family = "monospace"
style = "Regular"
[font.offset]
x = 0
y = 0

[hints]
alphabet = "jfkdls;ahgurieowpq"

[[hints.enabled]]
command = "xdg-open"
post_processing = true
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001f\u007f-<>\"\\s{-}\\^⟨⟩`]+"
[hints.enabled.binding]
key = "U"
mods = "Control|Shift"
[hints.enabled.mouse]
enabled = true
mods = "None"

[mouse]
hide_when_typing = false

[scrolling]
history = 10000
multiplier = 1

[selection]
save_to_clipboard = false
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[window]
decorations = "full"
dynamic_padding = false
dynamic_title = true
opacity = 0.95
startup_mode = "Windowed"
title = "Terminal"
[window.class]
general = "Terminal"
instance = "Terminal"
[window.dimensions]
columns = 0
lines = 0
[window.padding]
x = 0
y = 0
[window.position]
x = 0
y = 0

[general]
live_config_reload = true
