#!/bin/bash
# battery script by Vagos Labrou

BTR_DVC_FLDR="/sys/class/power_supply"

for battery in $BTR_DVC_FLDR/BAT*; do 
    CAPACITY=$(cat $battery/capacity)
    echo  $CAPACITY% $(cat $battery/status)
done
