directory: /mnt/dj/music
library: ~/.local/share/beets/library.db
import:
  move: yes
paths:
  singleton: $artist/$title
plugins:
  - edit
  - info
  - describe
  - badfiles
  - fromfilename  
  - fetchart 
  - lastgenre
  - embedart 
  - web 
  - random 
  - duplicates
  - fuzzy 
  - play 
  - playlist
  - scrub
  - spotify 
  - discogs
  - ytimport

# Plugin-specific configuration

bandcamp: 
  art: true

lastgenre:
  count: 1
  prefer_specific: yes
  title_case: yes
  source: track

duplicates:
  keys:
    - artist
    - title
    - album

badfiles:
    check_on_import: yes
    commands:
        flac: flac --test --warnings-as-errors --silent
        opus: opusinfo -q
    show_output: false

ytimport:
  directory: ~/.cache/beets/ytmusic
  import: true
  reimport: false
  format: bestaudio/best
  likes: false
  auth_headers: ~/.config/beets/headers
  set:
    loved: true
  min_length: 1
  max_length: 7200 
  max_length_nochapter: 900
  split_tracks: true
  group_albums: true
  quiet_fallback: skip 
