directory: /mnt/dj/music
library: ~/.local/share/beets/library.db
import:
  move: yes
paths:
  singleton: $artist/$title
plugins:
  - edit
  - info
  - describe
  - badfiles
  - fromfilename  
  - fetchart 
  - lastgenre
  - embedart 
  - web 
  - random 
  - duplicates
  - fuzzy 
  - play 
  - playlist
  - autobpm
  - spotify 
  - discogs
  - ytimport

# Plugin-specific configuration

bandcamp: 
  art: true

lastgenre:
  count: 1
  prefer_specific: yes
  title_case: no
  source: track
